# roles/wireguard/handlers/main.yml

- name: Restart WireGuard
  systemd:
    name: "wg-quick@{{ wg_interface }}"
    state: restarted
  become: true

- name: Save iptables rules
  command: netfilter-persistent save
  become: true
